// containers/projects/filters.vue
<template>
  <div class="filters">
    <TextField
      v-model="search"
      placeholder="Type to search"
      item="img"
      src="/images/icons/search.svg"
    />

    <div class="dropdowns">
      <Dropdown
        :chevron="false"
        class="order-options"
      >
        <template v-slot:label>
          <OrderIcon class="mr" />
          {{ orderBy || 'order' }}
        </template>
        <RadioGroup
          v-model="ordering"
          :items="orderings"
          :with-labels="true"
          name="ordering"
        />
      </Dropdown>
      <Dropdown
        :chevron="false"
        right
      >
        <template v-slot:label>
          <FilterIcon class="mr" />
          filters
          <span class="dot active small" />
        </template>
        <Button @click="$store.dispatch('projects/clearFilters')" danger>clear filters</Button>
        <FiltersAccordion />
      </Dropdown>
    </div>
  </div>
</template>

<script>
  import { mapState } from 'vuex';
  import RadioGroup from '@/components/ui/radio-group';
  import TextField from '@/components/ui/text-field';
  import Dropdown from '@/components/ui/dropdown';
  import Button from '@/components/ui/button';
  import FilterIcon from '@/static/images/icons/filter.svg';
  import OrderIcon from '@/static/images/icons/order.svg';
  import FiltersAccordion from '@/containers/projects/filters-accordion';

  export default {
    name: 'Filters',
    components: {
      FiltersAccordion,
      RadioGroup,
      TextField,
      Dropdown,
      Button,
      FilterIcon,
      OrderIcon,
    },
    data() {
      return {
        orderings: [
          'most recent',
          'least recent',
          'most valuable',
          'least valuable',
        ].map(label => ({label, value: label})),
      };
    },
    computed: {
      ...mapState('projects', ['filters', 'orderBy']),
      search: {
        get() {
          return this.filters.search;
        },
        set(value) {
          return this.$store.commit('projects/changeFilter', {type: 'search', value});
        },
      },
      ordering: {
        get() {
          return {label: this.orderBy, value: this.orderBy};
        },
        set(option) {
          this.$store.commit('projects/changeField', {type: 'orderBy', value: option.value});
        },
      },
    },
  };
</script>

// src/containers/store/filters.svelte
<script>
  import TextField from 'ui/text-field.svelte';
  import Dropdown from 'ui/dropdown.svelte';
  import Dot from 'ui/dot.svelte';
  import Button from 'ui/button.svelte';
  import RadioGroup from 'ui/radio-group.svelte';

  import {orders, selectedOrder, selectOrder} from '@/store/store';
</script>

<div class="filters">
  <TextField item>
    <svg src="images/icons/search.svg" class="item" />
  </TextField>
  <div class="dropdowns">
    <Dropdown chevron={false} wrapperclass="order-options">
      <svg slot="label" src="images/icons/order.svg" class="mr" />
      <span slot="label" class="tight">order</span>
      <span slot="label" class="regular">most expensive first</span>
      <RadioGroup
          selected={$selectedOrder}
          items={$orders}
          isLabel
          on:change="{(e) => selectOrder(e.detail)}"
      />
    </Dropdown>

    <Dropdown chevron={false} right>
      <svg slot="label" src="images/icons/filter.svg" class="mr" />
      <span slot="label">filters</span>
      <span slot="label"><Dot active small /></span>
      <Button danger>Clear filters</Button>
      <ul>
        <li class="filter price">
          <div>
            <span class="name">price</span>
            <div class="align-center">
              <TextField classname="no-spinner" type="number" />
              <span class="ml mr">–</span>
              <TextField classname="no-spinner" type="number" />
            </div>
          </div>
          <Button classname="mt">
            <svg src="images/icons/tag.svg" class="icon mr" />
            show affordable
          </Button>
        </li>
        <li class="filter colors">
          <span class="name">colors</span>

        </li>
      </ul>
    </Dropdown>
  </div>
</div>
