// pages/store/index.vue
<template>
  <div :class="{'modal-open': open}">
    <div class="material">
      <StoreTagline />
      <section id="store-top" class="shop padded">
        <Filters />
        <Ordering />

        <div v-if="items.length === 0" class="empty">
          <figure>
            <img class="picture" src="/images/store/no-products.svg" alt="" />
            <figcaption>
              <div class="title">No items found...</div>
              Try raiding 319 or a different filter
            </figcaption>
          </figure>
        </div>

        <div v-else class="cards">
          <StoreCard
            v-for="item in items"
            :key="item.id"
            v-bind="item"
            :toggle-modal="toggleModal"
          />
        </div>

        <Pagination v-model="currentPage" :pageCount="pageCount" />
      </section>

      <p class="link-bottom padded">
        Lacking innopoints?
        <nuxt-link to="/projects">Volunteer on projects</nuxt-link> to fill in the shortage!
      </p>
    </div>
    <ProductModal
      v-if="open"
      :product="product"
    />
  </div>
</template>

<script>
  import StoreCard from "../../components/store/card";
  import StoreTagline from "../../components/store/tagline";
  import Filters from '@/containers/store/filters';
  import Ordering from '@/components/store/filters/ordering';
  import Pagination from '@/components/pagination';

  export default {
    head: {
      title: 'InnoStore',
    },
    components: {
      StoreCard,
      StoreTagline,
      Filters,
      Ordering,
      ProductModal: () => import('../../containers/store/product-modal'),
      Pagination,
    },
    data() {
      return {
        open: false,
        product: null,
        currentPage: 1,
        itemsPerPage: 20,
      };
    },
    computed: {
      products() {
        return this.$store.getters['store/products'];
      },
      pageCount() {
        return Math.ceil(this.products.length / this.itemsPerPage);
      },
      items() {
        const begin = this.itemsPerPage * (this.currentPage - 1);
        const end = begin + this.itemsPerPage;
        return this.products.slice(begin, end);
      },
    },
    watch: {
      $route() {
        if(this.$route.query.id) {
          this.product = this.items.find(x => x.id === parseInt(this.$route.query.id));
          if(this.product !== undefined)
            this.open = true;
        }
        else {
          this.open = false;
        }
      },
    },
    asyncData ({ query, redirect }) {
      if(query.id) redirect('/store/' + query.id);
    },
    methods: {
      toggleModal() {
        this.open = !this.open;
      },
    },
  };
</script>

<style lang="scss" src="../../static/css/store/index.scss" />

// src/routes/store.svelte
<script>
  import Layout from '@/layouts/default.svelte';
  import Tagline from '@/containers/store/tagline.svelte';

  const items = [];
</script>

<svelte:head>
  <title>Store – Innopoints</title>

  <!-- Store styles -->
  <link rel="stylesheet" href="css/page-components/header.css" />
  <link rel="stylesheet" href="css/page-components/tagline.css" />
  <link rel="stylesheet" href="css/page-components/filters.css" />
  <link rel="stylesheet" href="css/page-components/empty-state.css" />
  <link rel="stylesheet" href="css/store/filters-spec.css" />
  <link rel="stylesheet" href="css/store/main.css" />
  <link rel="stylesheet" href="css/view-product/main.css" />
  <link rel="stylesheet" href="css/page-components/pagination.css" />
  <link rel="stylesheet" href="css/page-components/modal-dialog.css" />
  <link rel="stylesheet" href="css/page-components/footer.css" />

  <!-- Projects styles -->
  <link rel="preload" href="css/projects/filters-spec.css" as="style" />
  <link rel="preload" href="css/projects/main.css" as="style" />

  <!-- Home styles -->
  <link rel="preload" href="css/home/main.css" as="style" />
  <link rel="preload" href="css/home/header.css" as="style" />
  <link rel="preload" href="css/home/tagline.css" as="style" />
  <link rel="preload" href="css/home/how-to.css" as="style" />
  <link rel="preload" href="css/home/options.css" as="style" />
  <link rel="preload" href="css/home/store.css" as="style" />
  <link rel="preload" href="css/home/contacts.css" as="style" />
</svelte:head>

<Layout>
  <Tagline />

  <section id="store-top" class="shop padded">
    <!--<Filters />
    <Ordering />-->

    {#if items.length === 0}
      <div lass="empty">
        <figure>
          <img class="picture" src="/images/store/no-products.svg" alt="" />
          <figcaption>
            <div class="title">No items found...</div>
            Try raiding 319 or a different filter
          </figcaption>
        </figure>
      </div>
    {:else}
      <div class="cards">
        {#each items as item, i (item.id)}
          <!-- <StoreCard {...item} />-->
        {/each}
      </div>
    {/if}

    <!--<Pagination v-model="currentPage" :pageCount="pageCount" />-->
  </section>

  <p class="link-bottom padded">
    Lacking innopoints?
    <a href="/projects">Volunteer on projects</a>
    to fill in the shortage!
  </p>
</Layout>
