// src/routes/projects/index.svelte
<script>
  import Layout from '@/layouts/default.svelte';
  import Tagline from '@/containers/projects/tagline.svelte';
  import Button from 'ui/button.svelte';

  const projects = [];
</script>

<svelte:head>
  <title>Projects – Innopoints</title>

  <!-- Styles for Projects page -->
  <link rel="stylesheet" href="css/page-components/header.css" />
  <link rel="stylesheet" href="css/page-components/tagline.css" />
  <link rel="stylesheet" href="css/page-components/empty-state.css" />
  <link rel="stylesheet" href="css/page-components/filters.css" />
  <link rel="stylesheet" href="css/page-components/footer.css" />
  <link rel="stylesheet" href="css/projects/filters-spec.css" />
  <link rel="stylesheet" href="css/projects/main.css" />

  <!-- Styles for the landing -->
  <link rel="preload" href="css/home/main.css" as="style" />
  <link rel="preload" href="css/home/header.css" as="style" />
  <link rel="preload" href="css/home/tagline.css" as="style" />
  <link rel="preload" href="css/home/how-to.css" as="style" />
  <link rel="preload" href="css/home/options.css" as="style" />
  <link rel="preload" href="css/home/store.css" as="style" />
  <link rel="preload" href="css/home/contacts.css" as="style" />

  <!-- Store styles -->
  <link rel="preload" href="css/store/filters-spec.css" as="style" />
  <link rel="preload" href="css/store/main.css" as="style" />
  <link rel="preload" href="css/view-product/main.css" as="style" />
  <link rel="preload" href="css/page-components/pagination.css" as="style" />
  <link rel="preload" href="css/page-components/modal-dialog.css" as="style" />
</svelte:head>

<Layout>
  <Tagline />

  <section class="projects padded">
    <h1>Ongoing projects</h1>

    <!--<Filters />
    <Ordering />-->

    {#if projects.length === 0}
      <div class="empty">
        <figure>
          <img
            class="picture"
            src="images/projects/no-projects.svg"
            alt="no projects found" />
          <figcaption>
            <div class="title">No projects found...</div>
            But you can
            <a href="/project/new">create a project</a>
            right now!
          </figcaption>
        </figure>
      </div>
    {:else}
      <div class="cards">
        {#each projects as project, i (project.id)}
          <!--<Project {...project} />-->
        {/each}
      </div>
    {/if}
  </section>

  <div class="justify-center">
    <Button>
      <svg src="images/icons/book-open.svg" class="mr" />
      see past projects
    </Button>
  </div>

  <p class="link-bottom padded">
    What’s so cool about being a volunteer? The
    <nuxt-link to="/store">InnoStore</nuxt-link>
    has your answers!
  </p>
</Layout>

// pages/projects/index.vue
<template>
  <div class="material">
    <ProjectsTagline />

    <section class="projects padded">
      <h1>Ongoing projects</h1>

      <Filters />
      <Ordering />

      <div v-if="projects.length === 0" class="empty">
        <figure>
          <img class="picture" src="/images/projects/no-projects.svg" alt="" />
          <figcaption>
            <div class="title">No projects found...</div>
            But you can <nuxt-link to="project-edit">create a project</nuxt-link> right now!
          </figcaption>
        </figure>
      </div>

      <div class="cards">
        <Project
          v-for="(project, i) in projects"
          :key="i"
          v-bind="project"
        />
      </div>
    </section>

    <div class="justify-center">
      <Button img="/images/icons/book-open.svg" label="see past projects" />
    </div>

    <p class="link-bottom padded">
      What’s so cool about being a volunteer? The <nuxt-link to="/store">InnoStore</nuxt-link> has your answers!
    </p>
  </div>
</template>

<script>
  import {mapGetters} from 'vuex';
  import Filters from '@/containers/projects/filters';
  import ProjectsTagline from '@/components/projects/tagline';
  import Ordering from '@/components/projects/filters/ordering';
  import Button from '@/components/ui/button';

  export default {
    head: {
      title: 'Project Browser',
      meta: [
        { hid: 'description', name: 'description',
          content: `Search for volunteering opportunities with project browser page` },
      ],
    },
    components: {
      Button,
      Ordering,
      Filters,
      ProjectsTagline,
      Project: () => import('../../components/projects/project'),
    },
    data() {
      return {
        projectsPerPage: 8,
        currentPage: 1,
      };
    },
    computed: {
      ...mapGetters({
        allProjects: 'projects/projects',
      }),
      pageCount() {
        return Math.ceil(this.allProjects.length / this.projectsPerPage);
      },
      projects() {
        const page = this.currentPage - 1;
        const start = this.projectsPerPage * page;
        const end = start + this.projectsPerPage;
        return this.allProjects.slice(start, end);
      },
    },
  };
</script>

<style lang="scss" src="../../static/css/projects/index.scss" />
