// containers/ui/buttons.vue
<template>
  <Card>
    <h1>Buttons</h1>
    <div class="showcase">
      <Button
        :click="alert"
        label="simple"
      />

      <Button
        :click="alert"
        label="danger"
        danger
      />

      <Button
        :click="alert"
        label="filled"
        filled
      />

      <Button
        :click="alert"
        label="outline"
        outline
      />
      <Button
        :click="alert"
        label="filled danger"
        filled
        danger
      />

      <Button
        :click="alert"
        label="outline danger"
        outline
        danger
      />

      <Button
        :click="alert"
        label="outline disable"
        outline
        disabled
      />
    </div>
    <hr />

    <h1>Button-Links</h1>
    <div class="showcase">
      <Button
        link
        href="/"
        label="simple"
      />

      <Button
        link
        away
        href="http://example.com"
        label="danger"
        danger
      />

      <Button
        link
        href="#"
        label="filled"
        filled
      />

      <Button
        link
        href="#"
        label="outline"
        outline
      />

      <Button
        link
        href="#"
        label="filled danger"
        filled
        danger
      />

      <Button
        link
        href="#"
        label="filled danger"
        outline
        danger
      />
    </div>
    <hr />

    <h1>With icons</h1>
    <div class="showcase">
      <Button
        round
        img="/images/icons/calendar.svg"
      />

      <Button
        round
        normal
        img="/images/icons/calendar.svg"
      />

      <Button
        round
        badge
        img="/images/icons/calendar.svg"
      />

      <Button
        round
        outline
        img="/images/icons/calendar.svg"
      />

      <Button
        round
        filled
        img="/images/icons/calendar.svg"
      />

      <Button
        round
        label="with label"
        img="/images/icons/calendar.svg"
      />

      <Button
        round
        filled
        label="with label"
        img="/images/icons/calendar.svg"
      />

      <Button
        round
        outline
        label="with label"
        img="/images/icons/calendar.svg"
      />
    </div>
  </Card>
</template>

<script>
  import Card from '../../components/ui/card';
  import Button from '../../components/ui/button';
  export default {
    components: {
      Button,
      Card,
    },
    methods: {
      alert() {
        alert('Some text for the show');
      },
    },
  };
</script>

// src/containers/ui/buttons.svelte
<script>
  import Button from 'ui/button.svelte';
  import Card from 'ui/card.svelte';
</script>

<Card id="buttons" class="todo">
  <h1>Buttons</h1>
  <div class="showcase">
    <Button filled href="#" away>link</Button>
    <Button filled>button</Button>
    <Button outline filled href="#">link</Button>
    <Button href="#">link</Button>
    <Button disabled filled>disabled</Button>
    <Button disabled outline>disabled</Button>
    <Button disabled>disabled</Button>
  </div>
  <div class="showcase">
    <Button filled>
      button
      <svg src="images/icons/flag.svg" class="ml icon" />
    </Button>
    <Button href="#">
      <svg src="images/ui-kit-page/calendar.svg" class="mr icon" />
      button
    </Button>
  </div>
  <div class="showcase">
    <Button round badge>
      <svg src="images/ui-kit-page/bell.svg" />
    </Button>
    <Button round normal>
      <svg src="images/ui-kit-page/x.svg" />
    </Button>
    <Button outline round normal>
      <svg src="images/ui-kit-page/x.svg" />
    </Button>
    <Button filled chevron>chevron</Button>
  </div>
  <hr />
  <div class="showcase">
    <Button filled danger>
      <svg src="images/icons/move.svg" class="mr" />
      button
    </Button>
    <Button href="#" outline danger>button</Button>
    <Button href="#" danger>button</Button>
  </div>
</Card>
