// containers/ui/checkboxes.vue
<template>
  <card class="checkboxes">
    <h1>Checkboxes group</h1>
    <div class="showcase">
      <checkbox-group :items="items" :click="handleCheckboxChange" />
    </div>
  </card>
</template>

<script>
  import Card from '../../components/ui/card';
  import CheckboxGroup from '../../components/ui/checkbox-group';

  const items = [
    {
      checked: true,
      label: 'checkbox #1'
    },
    {
      checked: false,
      label: 'checkbox #2'
    },
    {
      checked: true,
      label: 'checkbox #3'
    },
  ];

  export default {
    components: {
      CheckboxGroup,
      Card
    },
    data() {
      return {
        items
      };
    },
    methods: {
      handleCheckboxChange(newItems) {
        this.items = newItems;
      }
    }
  };
</script>

// src/containers/ui/checkboxes.svelte
<script>
  import CheckboxGroup from 'ui/checkbox-group.svelte';
  import Card from 'ui/card.svelte';

  const checkboxes = [
    {
      id: 0,
      color: '#FF00FF',
      label: 'one checkbox',
    },
    {
      id: 1,
      color: '#FFFFFF',
      label: 'two checkbox',
    },
    {
      id: 2,
      color: '#000000',
      label: 'three checkbox',
    },
  ];
</script>

<Card id="checkboxes">
  <h1>Checkboxes</h1>
  <div class="showcase">
    <CheckboxGroup
        items={checkboxes}
        name="checkbox-1"
    />
  </div>
  <div class="showcase">

    <hr />

    <CheckboxGroup
        colored
        items={checkboxes}
        checked={[checkboxes[1]]}
        name="checkbox-2"
    />

    <hr />

    <CheckboxGroup
        labeled
        items={checkboxes}
        checked={checkboxes}
        name="checkbox-3"
    />
  </div>
</Card>
