// src/components/common/tagline.svelte
<script>
  import { Headline, Subhead } from 'attractions';

  export let imageURL;
  export let headline;
  export let subhead;
</script>

<section class="tagline padded">
  <img src={imageURL} class="hide-tb picture" alt="" />
  <div>
    <Headline>{headline}</Headline>
    <Subhead>
      <p>{subhead}</p>
      <slot />
    </Subhead>
  </div>
</section>

<style src="../../../static/css/components/tagline.scss"></style>

// components/events/tagline.vue
<template>
  <section class="tagline padded">
    <img src="/images/events/voxel-volunteering.png" class="hide-tb picture" />
    <div>
      <div class="headline">Become a volunteer</div>
      <div class="subhead">
        If you’re seeking an opportunity to contribute to the wonderful world of events,
        you’re in the right place!
      </div>
    </div>
  </section>
</template>

<script>
  export default {
    name: "EventsTagline",
  };
</script>
