// src/containers/profile/timeline.svelte
<script>
  import Button from 'ui/button.svelte';
  import Entry from '@/components/profile/timeline-entry.svelte';
  import timeline from '@/constants/profile/timeline';

  export let loadMore = false;
</script>

<div class="timeline">
  <slot />

  {#each timeline as entry, i (i)}
    <Entry type={entry.type} action={entry.action} important={entry.important || false} />
  {/each}

  {#if loadMore}
    <Button classname="more">
      <svg src="images/icons/more-horizontal.svg" class="icon mr-2" />
      more
    </Button>
  {/if}
</div>

// components/profile/timeline.vue
<template>
  <div class="timeline">
    <slot />

    <button
      v-if="load"
      @click="handleLoadClick"
      v-ripple="'rgba(56, 120, 0, .25)'"
      type="button"
      class="btn more"
    >
      <MoreIcon class="icon mr-2" />
      more
    </button>
  </div>
</template>

<script>
  import MoreIcon from '@/static/images/icons/more-horizontal.svg';

  export default {
    name: 'Timeline',
    components: {
      MoreIcon,
    },
    props: {
      load: {
        type: Boolean,
        default: false,
      },
      handleLoad: Function,
    },
    methods: {
      handleLoadClick() {
        if (this.handleLoad) this.handleLoad();
      },
    },
  };
</script>
