// containers/profile/statistics.vue
<template>
  <section class="statistics">
    <div class="period">
      <span class="hide-tb">Showing statistics</span>
      <Dropdown>
        <template v-slot:label>
          {{ activePeriod.label }}
        </template>
        <span class="label">Period of statistics</span>
        <ul class="mt">
          <li
            v-for="period in periods"
            :key="period.id"
          >
            <Button :label="period.label" @click="changePeriod(period)" />
          </li>
        </ul>
        <hr data-text="or" />
        <Button label="select date range" img="/images/icons/calendar.svg" />
      </Dropdown>
    </div>

    <Button img="/images/icons/file-text.svg" label="create a volunteer report" />

    <TopStats />

    <CompetencesStats />
  </section>
</template>

<script>
  import Dropdown from '../../components/ui/dropdown';
  import Button from '../../components/ui/button';
  import TopStats from '@/components/profile/top-stats';
  import CompetencesStats from '@/components/profile/competences-stats';
  import periods from '@/constants/profile/stats-period';

  export default {
    name: 'ProfileStatistics',
    components: {
      CompetencesStats,
      TopStats,
      Button,
      Dropdown,
    },
    data() {
      return {
        periods,
        activePeriod: periods[0],
      };
    },
    methods: {
      changePeriod(period) {
        this.activePeriod = period;
      },
    },
  };
</script>

<style>
  .statistics {
    display: block !important;
  }
</style>

// src/containers/profile/statistics.svelte
<script>
  import { createEventDispatcher } from 'svelte';
  import Button from 'ui/button.svelte';
  import PeriodPicker from '@/components/common/period-picker.svelte';
  import CompetencesChart from '@/components/profile/competences-chart.svelte';
  import datePeriods from '@/constants/date-periods.js';

  export let statistics;
  export let competences;

  let selectedPeriod = datePeriods[2];

  const dispatch = createEventDispatcher();

  function indexify(objectArray) {
    const map = new Map();
    for (let object of objectArray) {
      map.set(object.id, object.amount);
    }
    return map;
  }
</script>

<section class="statistics">
  <div class="period">
    <span class="hide-tb">Showing statistics</span>
    <PeriodPicker
      label="Period of statistics"
      on:period-change={(e) => { selectedPeriod = e.detail; dispatch('period-change', e.detail); }}
    />
    {#if false}
      <Button on:click={() => dispatch('create-report', selectedPeriod)}>
        <svg src="images/icons/file-text.svg" class="mr" />
        create a volunteer report
      </Button>
    {/if}
  </div>
  <div class="top-stats">
    <div class="stat">
      <header>
        <svg src="images/icons/clock.svg" class="icon" />
        {statistics.hours} volunteering hours
      </header>
      <div class="details">{statistics.positions} volunteering positions handled</div>
    </div>
    <div class="stat">
      <header>
        <svg src="images/icons/star.svg" class="icon" />
        Volunteer rating
        <span class="rating">{statistics.rating}</span>
      </header>
    </div>
  </div>
  <div class="stat competences">
    <header>
      <svg src="images/icons/bar-chart-2.svg" class="icon" />
      Developed competences
    </header>
    <CompetencesChart {competences} values={indexify(statistics.competences)} />
  </div>
</section>
