// containers/profile/tabs.vue
<template>
  <nav class="tabs">
    <label @click="$emit('change', 'T')" v-ripple="'rgba(56, 120, 0, .25)'" class="tab">
      <input
        type="radio"
        name="tabs"
        value="timeline"
        checked
      />
      <div class="icon">Timeline</div>
    </label>
    <label @click="$emit('change', 'S')" v-ripple="'rgba(56, 120, 0, .25)'" class="tab">
      <input type="radio" name="tabs" value="statistics" />
      <div class="icon">Statistics</div>
    </label>
    <label @click="$emit('change', 'N')" v-ripple="'rgba(56, 120, 0, .25)'" class="tab">
      <input type="radio" name="tabs" value="notifications" />
      <div class="icon">Notifications</div>
    </label>
  </nav>
</template>

<script>
  export default {
    name: 'ProfileTabs',
  };
</script>

// src/containers/profile/tabs.svelte
<script>
  import { createEventDispatcher } from 'svelte';

  let dispatch = createEventDispatcher();
  function changeTab(tab) {
    dispatch('change', tab);
  }
</script>

<nav class="tabs">
  <label on:click="{() => changeTab('T')}" class="tab">
    <input
        type="radio"
        name="tabs"
        value="timeline"
        checked
    />
    <!--TODO: Add ripple on buttons like in vue: v-ripple="'rgba(56, 120, 0, .25)'" -->
    <div class="icon">Timeline</div>
  </label>
  <label on:click="{() => changeTab('S')}" class="tab">
    <input type="radio" name="tabs" value="statistics" />
    <div class="icon">Statistics</div>
  </label>
  <label on:click="{() => changeTab('N')}" class="tab">
    <input type="radio" name="tabs" value="notifications" />
    <div class="icon">Notifications</div>
  </label>
</nav>
