// containers/profile/timeline.vue
<template>
  <Timeline :class="{collapsed}" load>
    <TimelineEntry
      v-for="(action, i) in timeline"
      :key="i"
      :type="action.type"
      :action="action.action"
      :important="action.important || false"
    />
  </Timeline>
</template>

<script>
  import Timeline from '@/components/profile/timeline';
  import TimelineEntry from '@/components/profile/timeline-entry';
  import timeline from '@/constants/profile/timeline';

  export default {
    name: 'ProfileTimeline',
    components: {
      TimelineEntry,
      Timeline,
    },
    data() {
      return {
        collapsed: false,
        timeline,
      };
    },
    methods: {
      collapse() {
        this.collapsed = !this.collapsed;
      },
    },
  };
</script>

// src/containers/profile/timeline.svelte
<script>
  import Button from 'ui/button.svelte';
  import Entry from '@/components/profile/timeline-entry.svelte';
  import timeline from '@/constants/profile/timeline';

  export let loadMore = false;
</script>

<div class="timeline">
  <slot />

  {#each timeline as entry, i (i)}
    <Entry type={entry.type} action={entry.action} important={entry.important || false} />
  {/each}

  {#if loadMore}
    <Button classname="more">
      <svg src="images/icons/more-horizontal.svg" class="icon mr-2" />
      more
    </Button>
  {/if}
</div>
