// src/containers/store/tagline.svelte
<section class="tagline padded">
  <img
    src="images/store/voxel-trolley.png"
    class="hide-tb picture"
    alt="store image" />
  <div>
    <div class="headline">InnoStore</div>
    <div class="subhead">
      The place where your hard work and proactivity turns into cool merch of
      Innopolis University.
    </div>
  </div>
</section>

// components/shop/tagline.vue
<template>
  <section class="tagline padded">
    <img src="/images/shop/voxel-trolley.png" class="hide-tb picture" />
    <div>
      <div class="headline">InnoStore</div>
      <div class="subhead">
        The place where your hard work and proactivity turns into cool merch of Innopolis University
      </div>
    </div>
  </section>
</template>

<script>
  export default {
    name: "ShopTagline",
  };
</script>
