// src/components/ui/card.svelte
<script>
  export let id = null;
  export let img = null;
  export let imgWrap = true;
  export let color = '#FFF';
</script>

<div class="card" class:with-image={img} {id}>
  {#if img}
    {#if imgWrap}
      <div class="image">
        <slot name="image">
          <img src={img} style="{'background: ' + color}" class="image" alt="" />
        </slot>
        <slot name="radio" />
      </div>
    {:else}
      <slot name="image">
        <img src={img} style="{'background: ' + color}" class="image" alt="" />
      </slot>
    {/if}
    <div class="content">
      <slot />
    </div>
  {:else}
    <slot />
  {/if}
</div>

// components/ui/card.vue
<template>
  <div :class="img ? 'with-image' : ''" class="card">
    <div class="image">
      <img
        v-if="img"
        :src="img"
        :style="'background: ' + color"
        class="image"
      />
      <slot name="radio" />
    </div>
    <div v-if="img" class="content">
      <slot />
    </div>
    <template v-else>
      <slot />
    </template>
  </div>
</template>

<script>
  export default {
    name: 'Card',
    props: {
      img: {
        type: String,
        default: '',
      },
      color: {
        type: String,
        default: '#FFF',
      },
    },
  };
</script>
