// src/components/ui/dialog.svelte
<script>
  import Button from 'ui/button.svelte';
  import dynamic from 'ui/utils/dynamic-transition.js';
  import { fly } from 'svelte/transition';
  export let classname = '';
  export let isDanger = false;
  export let isNotice = false;

  export let title = null;
  export let closeCallback = null;
  export let transition = fly;
  export let transitionOptions = { y: 10, duration: 150 };
</script>

<div
  class="dialog {classname}"
  class:danger={isDanger}
  class:notice={isNotice}
  transition:dynamic={{ transition, options: transitionOptions }}
>
  {#if closeCallback !== null}
    <Button isNormal isRound classname="close" on:click={closeCallback}>
      <svg src="/images/icons/x.svg" class="icon" />
    </Button>
  {/if}
  {#if title !== null}
    <div class="title">
      <slot name="icon" />
      {title}
    </div>
  {/if}
  <slot name="content" />
</div>

// components/ui/dialog.vue
<template>
  <div :class="type" class="dialog">
    <button @click="$emit('close')" class="btn normal round close">
      <img src="images/ui-kit/x.svg" />
    </button>
    <span class="title">
      <img :src="icons[type]" class="icon" />
      <slot name="title">{{ title }}</slot>
    </span>
    <p>
      <slot>{{ text }}</slot>
    </p>
    <div class="actions">
      <slot name="actions">
        <button
          v-for="(action, i) in actions"
          :key="i"
          v-bind="action"
          @click="action.onclick || function() {}"
          class="btn"
        >
          {{ action.text }}
        </button>
      </slot>
    </div>
  </div>
</template>

<script>
  export default {
    props: {
      danger: {
        type: Boolean,
        default: false,
      },
      notice: {
        type: Boolean,
        default: false,
      },
      title: {
        type: String,
        required: false,
      },
      text: {
        type: String,
        required: false,
      },
      actions: {
        type: Array,
        required: false,
        default: () => [],
      },
    },
    data() {
      return {
        icons: {
          '': '/images/ui-kit/award.svg',
          danger: '/images/ui-kit/alert-triangle.svg',
          notice: '/images/ui-kit/alert-triangle-green.svg',
        },
      };
    },
    computed: {
      type() {
        if(this.danger)
          return 'danger';
        if(this.notice)
          return 'notice';
        return '';
      },
    },
  };
</script>
