// src/components/ui/dropdown.svelte
<script>
  import Button from './button.svelte';

  export let label = '';
  export let right = false;
  export let chevron = true;
  export let btnclass = '';
  export let dropdownclass = '';
  export let nowrap = false;
  export let open = false;
  export const toggle = () => (open = !open);
</script>

<div class:open class="dropdown-shell">
  <Button on:click={toggle} class="handle {btnclass}">
    <slot name="label">{label}</slot>
    {#if chevron}
      <svg src="images/icons/chevron-down.svg" class="icon ml chevron" />
    {/if}
  </Button>
  <div class:right-edge={right} class="dropdown {dropdownclass}">
    {#if nowrap}
      <slot />
    {:else}
      <div class="relative-wrapper">
        <Button on:click={toggle} normal round btnclass="close">
          <svg src="images/icons/x.svg" />
        </Button>
        <slot />
      </div>
    {/if}
  </div>
</div>

// components/ui/dropdown.vue
<template>
  <div :class="isOpen && 'open'" class="dropdown-shell">
    <button
      @click="toggle"
      v-ripple="'rgba(56, 120, 0, .25)'"
      type="button"
      class="btn handle"
    >
      <slot name="opener" />
      <img v-if="chevron" src="/images/events/chevron-down.svg" class="chevron" />
    </button>
    <div :class="right && 'right-edge'" class="dropdown">
      <slot />
    </div>
  </div>
</template>

<script>
  export default {
    name: 'Dropdown',
    props: {
      open: {
        type: Boolean,
        default: false,
      },
      right: {
        type: Boolean,
        default: false,
      },
      chevron: {
        type: Boolean,
        default: true,
      },
    },
    data() {
      return {
        isOpen: this.open,
      };
    },
    methods: {
      toggle() {
        this.isOpen = !this.isOpen;
      },
    },
  };
</script>
