// src/components/common/labeled.svelte
<script>
  import { Label } from 'attractions';
  import classes from '@/utils/classes.js';

  let _class = null;
  export { _class as class };

  export let label;
  export let icon = false;
</script>

<div class:text={!icon} class={classes('labeled', _class)}>
  {#if icon}
    <div />
    <slot name="icon" />
    <Label>
      <slot name="label">{label}</slot>
    </Label>
    <slot />
  {:else}
    <Label>
      <slot name="label">{label}</slot>
    </Label>
    <slot />
  {/if}
</div>

<style src="../../../static/css/components/common/labeled.scss"></style>

// components/ui/labeled.vue
<template>
  <div :class="!icon && 'text'" class="labeled">
    <template v-if="icon">
      <!--eslint-disable-next-line-->
      <component :is="svg" />
      <div class="text">
        <span class="label">{{ label }}</span>
        <span>
          <slot />
        </span>
      </div>
    </template>

    <template v-else>
      <span class="label">{{ label }}</span>
      <span>
        <slot />
      </span>
    </template>
  </div>
</template>

<script>
  export default {
    name: 'Labeled',
    props: {
      icon: {
        type: String,
        default: null
      },
      label: {
        type: String,
        required: true
      }
    },
    computed: {
      svg() {
        if(this.icon) return () => import('../../static' + this.icon);
        return '';
      }
    }
  };
</script>
