// containers/home/options.vue
<template>
  <section class="options">
    <h2>How to get innopoints?</h2>
    <div
      v-for="(option, i) in options"
      :key="i"
      class="step"
    >
      <Step v-bind="option" />
    </div>
  </section>
</template>

<script>
  import Step from '../../components/home/option-step';
  import options from '../../constants/home/options';

  export default {
    components: {
      Step,
    },
    data() {
      return {
        options,
      };
    },
  };
</script>

// src/containers/home/options.svelte
<script>
  import options from '@/constants/home/options';
  import Step from '@/components/home/option-step.svelte';
</script>

<section class="options">
  <h2>How to get innopoints?</h2>
  {#each options as option, i (option.title)}
    <div class="step">
      <Step {...option} />
    </div>
  {/each}
</section>
