// containers/home/store.vue
<template>
  <section class="store container">
    <h2>How to spend innopoints?</h2>

    <div class="subtitle padded">
      The following items are the most popular among students.<br />
      Grab ‘em while they’re hot!
    </div>

    <div class="cards">
      <StoreCard
        v-for="item in topItems"
        :key="item.id"
        v-bind="item"
        is-short
      />
    </div>

    <div class="own-designs">
      Bright ideas for new merch are always welcome, so get in touch with us if you have some!
    </div>
  </section>
</template>

<script>
  import StoreCard from '../../components/store/card';
  import items from '../../constants/store';

  export default {
    components: {
      StoreCard,
    },
    data() {
      return {
        topItems: items.slice(0,3),
      };
    },
  };
</script>

// src/containers/home/store.svelte
<script>
  import StoreCard from '@/components/store/card.svelte';
  import items from '@/constants/store';
  const topItems = items.slice(0, 3);
</script>

<section class="store container">
  <h2>How to spend innopoints?</h2>

  <div class="subtitle padded">
    The following items are the most popular among students.
    <br />
    Grab ‘em while they’re hot!
  </div>

  <div class="cards">
    {#each topItems as item, i (item.id)}
      <StoreCard
        {...{ id: item.id, name: item.name, type: item.type, varieties: item.varieties, price: item.price }}
        short />
    {/each}
  </div>

  <div class="own-designs">
    Bright ideas for new merch are always welcome, so get in touch with us if
    you have some!
  </div>
</section>
