// src/components/ui/tabs.svelte
<script>
  import { createEventDispatcher } from 'svelte';
  export let classname = '';
  export let tabclass = '';
  export let iconclass = '';
  export let inputclass = '';

  export let values;
  export let value = null;
  export let labels = null;
  export let name;

  const dispatch = createEventDispatcher();

  if (values.length === 0) {
    console.error('Must have at least one item in the radio group.');
  }

  if (labels !== null && values.length !== labels.length) {
    console.error('Must have as many labels as there is values.');
  }
</script>

<nav class="tabs {classname}">
  {#each values as loopValue, i (i)}
    <label class="tab {tabclass}">
      <input
        type="radio"
        {name}
        class={inputclass}
        bind:group={value}
        value={loopValue}
        checked={loopValue === value}
        on:change={evt => dispatch('change', evt.target.value)}
      />
      <div class="icon {iconclass}">{labels === null ? loopValue : labels[i]}</div>
    </label>
  {/each}
</nav>

// containers/profile/tabs.vue
<template>
  <nav class="tabs">
    <label @click="$emit('change', 'T')" class="tab">
      <input
        type="radio"
        name="tabs"
        value="timeline"
        checked
      />
      <div class="icon">Timeline</div>
    </label>
    <label @click="$emit('change', 'S')" class="tab">
      <input type="radio" name="tabs" value="statistics" />
      <div class="icon">Statistics</div>
    </label>
    <label @click="$emit('change', 'N')" class="tab">
      <input type="radio" name="tabs" value="notifications" />
      <div class="icon">Notifications</div>
    </label>
  </nav>
</template>

<script>
  export default {
    name: 'ProfileTabs',
  };
</script>
