// src/components/projects/spots.svelte
<script>
  import Button from 'ui/button.svelte';
  import TextField from 'ui/text-field.svelte';

  import {filters, changeSpots} from '@/store/projects';
</script>

<li class="filter spots">
  <div class="align-center">
    <svg src="images/icons/users.svg" class="icon mr" />
    <span class="name">vacant spots</span>
  </div>
  <div class="align-center">
    <Button round on:click={() => changeSpots($filters.spots - 1)}>
      <svg src="images/icons/minus.svg" class="icon" />
    </Button>
    <TextField
        value={$filters.spots}
        type="number"
        classname="no-spinner"
        on:input={(e) => changeSpots(e.detail)}
    />
    <Button round on:click={() => changeSpots($filters.spots + 1)}>
      <svg src="images/icons/plus.svg" class="icon" />
    </Button>
  </div>
</li>

// components/events/filters/spots.vue
<template>
  <li class="filter spots">
    <div class="align-center">
      <img src="/images/events/users.svg" />
      <span class="name">vacant spots</span>
    </div>

    <div class="align-center">
      <Button @click="spots--" round>
        <img src="/images/events/minus.svg" />
      </Button>
      <TextField
        :min="0"
        v-model="spots"
        type="number"
        class="no-spinner"
      />
      <Button @click="spots++" round>
        <img src="/images/events/plus.svg" />
      </Button>
    </div>
  </li>
</template>

<script>
  import TextField from '@/components/ui/text-field';
  import Button from '@/components/ui/button';

  export default {
    name: 'Spots',
    components: {
      TextField,
      Button,
    },
    computed: {
      spots: {
        get() {
          return this.$store.state.events.filters.spots;
        },
        set(value) {
          this.$store.commit('events/changeFilter', {type: 'spots', value});
        },
      },
    },
  };
</script>
