// components/home/header.vue
<template>
  <header class="container">
    <img @click="resolution" src="/images/innou-logo.svg" class="logo" />
    <Button
      v-if="isAuth"
      link
      href="/profile"
      img="/images/icons/user.svg"
      round
      outline
    />
    <Button
      v-else
      @click="toggleAuth"
      label="sign in"
      outline
    />
  </header>
</template>

<script>
  import {mapState, mapActions} from 'vuex';
  import Button from '../ui/button';

  export default {
    name: "LandingHeader",
    components: { Button },
    computed: mapState({
      isAuth: state => state.user.isAuth,
    }),
    methods: {
      resolution: () => {
        alert(`You current browser screen resolution.
        Width: ${window.innerWidth}px, height: ${window.innerHeight}px`);
      },
      ...mapActions({toggleAuth: 'user/toggleAuth'}),
    },
  };
</script>

// src/components/home/header.svelte
<script>
  import { Button } from 'attractions';
  import NotificationCenter from 'src/components/common/notification-center.svelte';
  import { login } from 'src/utils/auth.js';

  export let user = null;
</script>

<header class="container">
  <img
    src="/images/innou-logo.svg"
    class="logo"
    alt="Innopolis University logo"
  />
  {#if user == null}
    <Button outline on:click={login}>sign in</Button>
  {:else}
    <div class="actions">
      <NotificationCenter />
      {#if user.is_admin}
        <Button href="/dashboard" round>
          <svg src="static/images/icons/grid.svg" />
        </Button>
      {:else}
        <Button href="/profile" round>
          <svg src="static/images/icons/user.svg" />
        </Button>
      {/if}
    </div>
  {/if}
</header>

<style src="../../../static/css/components/home/header.scss"></style>
