// components/home/option-step.vue
<template>
  <div class="container">
    <img :src="img" class="picture" />
    <div class="description">
      <span class="title">{{ title }}</span>
      <span class="subtitle">{{ subtitle }}</span>
      <Button
        v-if="buttonLink"
        :label="buttonText"
        :away="external"
        :href="buttonLink"
        :img="external ? '/images/icons/external-link.svg' : ''"
        link
        filled
      />
      <strong v-else>{{ buttonText }}</strong>
    </div>
  </div>
</template>

<script>
  import Button from '../ui/button';

  export default {
    components: { Button },
    props: {
      img: String,
      title: String,
      subtitle: String,
      buttonLink: {
        type: String,
        default: '#',
      },
      buttonText: String,
      external: {
        type: Boolean,
        required: false,
        default: false,
      },
    },
  };
</script>

// src/components/home/option-step.svelte
<script>
  import Button from 'ui/button.svelte';

  export let title = '';
  export let subtitle = '';
  export let img = '';
  export let buttonText = '';
  export let buttonLink = null;
  export let external = null;
</script>

<div class="container">
  <img src={img} class="picture" alt={title} />
  <div class="description">
    <span class="title">{title}</span>
    <span class="subtitle">{subtitle}</span>
    {#if buttonLink}
      <Button
        label={buttonText}
        away={external}
        href={buttonLink}
        img={external ? 'images/icons/external-link.svg' : ''}
        filled />
    {:else}
      <strong>{buttonText}</strong>
    {/if}
  </div>
</div>
