// src/components/products/balance.svelte
<script>
  import { s } from 'attractions/utils';

  export let value = null;
</script>

{#if value != null}
  <div class="balance">
    You have {value}
    <svg src="static/images/innopoint-sharp.svg" alt="innopoint{s(value)}" />
  </div>
{/if}

<style src="../../../static/css/components/products/balance.scss"></style>

// containers/shop/balance.vue
<template>
  <div class="balance-tooltip">
    You have {{ balance }}
    <Innopoint class="ml" />
  </div>
</template>

<script>
  import {mapState} from 'vuex';
  import Innopoint from '../../static/images/innopoint-sharp.svg';

  export default {
    name: 'BalanceTooltip',
    components: {
      Innopoint,
    },
    computed: {
      ...mapState({
        balance: state => state.user.balance,
      }),
    },
  };
</script>
