// src/components/products/product-card.svelte
<script>
  import { Card, Button, RadioGroup } from 'attractions';
  import Labeled from 'ui/labeled.svelte';
  import getBackground from '@/utils/optimal-color.js';
  import { groupByColor } from '@/utils/group-varieties.js';
  import { API_HOST_BROWSER } from '@/constants/env.js';

  export let id;
  export let name;
  export let type;
  export let price;
  export let varieties = [];
  export let short = false;

  let varietiesByColor = groupByColor(varieties);
  let colors = [...varietiesByColor.keys()];
  let selectedColor = colors[0];
  $: imageURL = (
    varietiesByColor.get(selectedColor)[0].images.length !== 0 ?
      API_HOST_BROWSER + varietiesByColor.get(selectedColor)[0].images[0]
      : '/images/create-product/placeholder.svg'
  );

  $: outOfStock = varieties.reduce((sum, variety) => variety.amount + sum, 0) === 0;
</script>

<div class="product-card">
  <Card tight>
    {#if colors.length > 1 && !short}
      <div class="image">
        <img
          src={imageURL}
          style={getBackground(selectedColor)}
          alt="Product cover"
        />
        <RadioGroup
          color
          bind:value={selectedColor}
          class="color-options"
          name="color-{id}"
          items={colors.map(val => ({ value: val }))}
        />
      </div>
    {:else}
      <img
        src={imageURL}
        style={getBackground(selectedColor)}
        alt="Product cover"
        class="image"
      />
    {/if}

    <div class="content">
      <div class="title">
        <div class="main">{name}</div>
        {#if outOfStock}
          <div class="out-of-stock">
            out of stock
          </div>
        {/if}
      </div>
      {#if type}
        <div class="subtitle">{type}</div>
      {/if}
      {#if short}
        <Button href="/products/{id}" outline>view</Button>
      {:else}
        <div class="card-row">
          <Labeled label="Price">
            <span class="content">
              <span class="price">{price}</span>
              <svg src="images/innopoint-sharp.svg" class="innopoint" />
            </span>
          </Labeled>
          <Button href="/products/{id}" outline>view</Button>
        </div>
      {/if}
    </div>
  </Card>
</div>

<style src="../../../static/css/components/products/product-card.scss"></style>

// containers/shop/product-card.vue
<template>
  <div>
    <div class="balance-tooltip">
      You have 1337&nbsp;
      <img src="images/innopoint.svg" class="ml" />
    </div>

    <div class="card product with-image">
      <button id="close-modal" class="btn normal round close">
        <img src="images/x.svg" />
      </button>
      <Carousel :images="getImages()" />
      <div class="content">
        <div class="title">{{ item.name }}</div>
        <div class="subtitle">{{ item.type }}</div>

        <div class="labeled text card-row">
          <span class="label">Description</span>
          <span>{{ item.description }}</span>
        </div>

        <div class="card-row">
          <div class="labeled text">
            <span class="label">Colors</span>
            <RadioGroup :items="item.varieties" :name="'color-' + item.id" class="radio-options" />
          </div>
          <Sizes />
        </div>

        <div class="card-row">
          <div class="labeled text">
            <span class="label">Price</span>
            <span class="price">
              {{ item.price }}
              <img src="images/innopoint.svg" />
            </span>
          </div>
          <div class="purchase">
            <div class="purchases">1488 purchases</div>
            <a class="btn filled" href="#">purchase</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
  import Carousel from "../../components/ui/carousel";
  import Sizes from "../../components/shop/sizes";
  import RadioGroup from "../../components/ui/radio-group";
  import items from "../../constants/store";

  export default {
    name: "ProductCard",
    components: {
      Carousel,
      Sizes,
      RadioGroup,
    },
    data() {
      return {
        item: items[0],
      };
    },
    methods: {
      getImages() {
        let images = [];
        this.item.varieties.filter(i => {
          images = images.concat(i.images);
        });
        return images;
      },
    },
  };
</script>
