// src/components/store/product-card.svelte
<script>
  import Card from 'ui/card.svelte';
  import Button from 'ui/button.svelte';
  import Labeled from 'ui/labeled.svelte';
  import RadioGroup from 'ui/radio-group.svelte';
  import getBackground from '@/utils/optimal-color.js';
  import { groupByColor } from '@/utils/group-varieties.js';
  import { API_HOST } from '@/constants/env';

  export let id;
  export let name;
  export let type;
  export let price;
  export let varieties = [];
  export let short = false;

  let varietiesByColor = groupByColor(varieties);
  let colors = [...varietiesByColor.keys()];
  let selectedColor = colors[0];
  let altText = 'Product image: ';
  if (type) {
    altText += `"${name}" ${type}`;
  } else {
    altText += name;
  }
</script>

<Card classname="with-image">
  {#if colors.length > 1 && !short}
    <div class="image">
      <img
        src={API_HOST + varietiesByColor.get(selectedColor)[0].images[0]}
        style="background: {getBackground(selectedColor)}"
        alt={altText}
      />
      <RadioGroup
        isColor
        values={colors}
        bind:value={selectedColor}
        classname="color-options"
        name="color-{id}"
      />
    </div>
  {:else}
    <img
      src={API_HOST + varietiesByColor.get(selectedColor)[0].images[0]}
      style="background: {getBackground(selectedColor)}"
      alt={altText}
      class="image"
    />
  {/if}

  <div class="content">
    <div class="title">{name}</div>
    {#if type}
      <div class="subtitle">{type}</div>
    {/if}
    {#if short}
      <Button href="/product/{id}" isOutline>view</Button>
    {:else}
      <div class="card-row">
        <Labeled label="Price">
          <span class="content">
            <span class="price">{price}</span>
            <svg src="images/innopoint-sharp.svg" class="innopoint" />
          </span>
        </Labeled>
        <Button href="/product/{id}" isOutline>view</Button>
      </div>
    {/if}
  </div>
</Card>

// containers/shop/product-card.vue
<template>
  <div>
    <div class="balance-tooltip">
      You have 1337&nbsp;
      <img src="images/innopoint.svg" class="ml" />
    </div>

    <div class="card product with-image">
      <button id="close-modal" class="btn normal round close">
        <img src="images/x.svg" />
      </button>
      <Carousel :images="getImages()" />
      <div class="content">
        <div class="title">{{ item.name }}</div>
        <div class="subtitle">{{ item.type }}</div>

        <div class="labeled text card-row">
          <span class="label">Description</span>
          <span>{{ item.description }}</span>
        </div>

        <div class="card-row">
          <div class="labeled text">
            <span class="label">Colors</span>
            <RadioGroup :items="item.varieties" :name="'color-' + item.id" class="radio-options" />
          </div>
          <Sizes />
        </div>

        <div class="card-row">
          <div class="labeled text">
            <span class="label">Price</span>
            <span class="price">
              {{ item.price }}
              <img src="images/innopoint.svg" />
            </span>
          </div>
          <div class="purchase">
            <div class="purchases">1488 purchases</div>
            <a class="btn filled" href="#">purchase</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
  import Carousel from "../../components/ui/carousel";
  import Sizes from "../../components/shop/sizes";
  import RadioGroup from "../../components/ui/radio-group";
  import items from "../../constants/store";

  export default {
    name: "ProductCard",
    components: {
      Carousel,
      Sizes,
      RadioGroup,
    },
    data() {
      return {
        item: items[0],
      };
    },
    methods: {
      getImages() {
        let images = [];
        this.item.varieties.filter(i => {
          images = images.concat(i.images);
        });
        return images;
      },
    },
  };
</script>
