// components/landing/footer.vue
<template>
  <footer>
    <div class="container space-between">
      <div class="left space-between">
        <div>
          <div class="title-container">
            <img src="/images/landing/innou-logo.png" class="logo" />
            <span class="title">Innopoints</span>
          </div>
          <div class="socials space-between">
            <a class="social" href="#"><img src="/images/landing/vk.svg" /></a>
            <a class="social" href="#"><img src="/images/landing/facebook.svg" /></a>
            <a class="social" href="#"><img src="/images/landing/twitter.svg" /></a>
            <a class="social" href="#"><img src="/images/landing/instagram.svg" /></a>
            <a class="social" href="#"><img src="/images/landing/youtube.svg" /></a>
          </div>
        </div>
        <span class="credits white">
          with credits to <br/>
          <a class="credit-link white" href="https://www.isometriclove.com/" target="_blank">Isometriclove</a>
          and <a class="credit-link white" href="https://www.humaaans.com/" target="_blank">Humaaans</a>
        </span>
      </div>

      <div class="right">
        <img src="/images/landing/pointer.png" />
        <nav>
          <div class="card search space-between shadow-2">
            search
            <img src="/images/landing/search.svg" />
          </div>
          <ul>
            <li>
              <nuxt-link to="/" class="white">browse the events</nuxt-link>
            </li>
            <li>
              <nuxt-link to="/" class="white">see the InnoStore</nuxt-link>
            </li>
          </ul>
        </nav>
      </div>
    </div>
  </footer>
</template>

<script>
  export default {
    name: "LandingFooter"
  };
</script>

// src/components/footer.svelte
<script>
  // import InnouIcon from '../../static/images/innou-icon.svg';
</script>

<footer>
  <div class="to-top">
    <button class="btn filled">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
        class="feather feather-arrow-up mr">
        <line x1="12" y1="19" x2="12" y2="5" />
        <polyline points="5 12 12 5 19 12" />
      </svg>
      back to top
    </button>
  </div>
  <div class="container space-between">
    <div class="left space-between">
      <div>
        <a href="/" class="title-container">
          <!-- innou-icon -->
          <svg src="../../static/images/innou-icon.svg" class="icon" />
          <!-- <InnouIcon class="icon"/> -->
          <span class="title">Innopoints</span>
        </a>
        <div class="socials space-between">
          <a href="https://vk.com/innopolisu">
            <img src="images/footer/vk.svg" alt="" />
          </a>
          <a href="https://www.facebook.com/InnopolisU">
            <img src="images/footer/facebook.svg" alt="" />
          </a>
          <a href="https://twitter.com/@InnopolisU">
            <img src="images/footer/twitter.svg" alt="" />
          </a>
          <a href="https://www.instagram.com/innopolisu/">
            <img src="images/footer/instagram.svg" alt="" />
          </a>
          <a href="https://www.youtube.com/user/InnopolisU">
            <img src="images/footer/youtube.svg" alt="" />
          </a>
        </div>
      </div>
      <span class="credits white">
        with credits to
        <br />
        <a href="https://isometriclove.com">Isometriclove</a>
        and
        <a href="https://humaaans.com">Humaaans</a>
      </span>
    </div>
    <div class="right">
      <img src="images/footer/pointer.svg" class="pointer" alt="" />
      <nav>
        <div class="search shadow-1">
          search
          <!-- search -->
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            class="feather feather-search">
            <circle cx="11" cy="11" r="8" />
            <line x1="21" y1="21" x2="16.65" y2="16.65" />
          </svg>
        </div>
        <ul>
          <li>
            <a class="white" href="/projects">browse the projects</a>
          </li>
          <li>
            <a class="white" href="/store">see the InnoStore</a>
          </li>
        </ul>
      </nav>
    </div>
  </div>
</footer>
