// src/components/projects/competences.svelte
<script>
  import Button from 'ui/button.svelte';
  import CheckboxGroup from 'ui/checkbox-group.svelte';
  import {filters, changeCompetences} from '@/store/projects';
  import competencesOptions from '@/constants/projects/competences';

  import { createEventDispatcher } from 'svelte';
  let dispatch = createEventDispatcher();

  export let open = false;
  $: value = open;
</script>

<li class:open={value} class="filter competences panel">
  <svg src="images/icons/tag.svg" class="icon mr" />
  <Button chevron classname="handle" on:click={() => dispatch('toggle')}>
    select competences
  </Button>
</li>
<section>
  <Button>clear all</Button>
  <CheckboxGroup
      labeled
      items={competencesOptions}
      value={$filters.competences}
      name="competences"
      on:change={(e) => changeCompetences(e.detail)}
  />
</section>

// components/projects/filters/competences.vue
<template>
  <li class="filter competences panel">
    <img src="/images/icons/label.svg" />
    <Accordion label="select competences">
      <Button @click="clearCompetences">clear all</Button>
      <CheckboxGroup
        :value="competences"
        @change="changeCompetence"
      />
    </Accordion>
  </li>
</template>

<script>
  import { mapState, mapActions } from 'vuex';
  import Accordion from '@/components/ui/accordion';
  import Button from '@/components/ui/button';
  import CheckboxGroup from '@/components/ui/checkbox-group';

  export default {
    name: 'Competences',
    components: {
      Accordion,
      Button,
      CheckboxGroup,
    },
    data() {
      return {
        open: false,
      };
    },
    computed: {
      ...mapState({
        competences: state => state.projects.filters.competences.map(c => ({...c, label: c.name})),
      }),
    },
    methods: {
      ...mapActions('projects', [
        'changeCompetence',
        'clearCompetences',
      ]),
    },
  };
</script>

<style scoped>
  label {
    cursor: pointer;
  }
</style>
