// src/components/store/card.svelte
<script>
  import Card from 'ui/card.svelte';
  import Button from 'ui/button.svelte';
  import Labeled from 'ui/labeled.svelte';

  export let id;
  export let name;
  export let type;
  export let price;
  export let varieties = [];
  export let short = false;

  $: selected = varieties[0];
</script>

<Card img={selected.images[0]} color={selected.background}>
  <!--  TODO: implement and use Radio group for this card -->
  <!--<template v-if="varieties.length > 1 && !isShort" v-slot:radio>
    <RadioGroup
        :items="varieties"
        :name="'color-' + id"
        v-model="selected"
        class="color-options"
    />
  </template>-->
  <div class="title">{name}</div>
  <span class="subtitle">{type}</span>
  {#if !short}
    <div class="card-row">
      <Labeled label="Price">
        {price}
        <svg src="images/innopoint-sharp.svg" class="innopoint" />
      </Labeled>
      <Button outline>view</Button>
    </div>
  {:else}
    <Button outline>view</Button>
  {/if}
</Card>

// components/store/card.vue
<template>
  <Card :img="selected.images[0]" :color="selected.background">
    <template v-if="varieties.length > 1 && !isShort" v-slot:radio>
      <RadioGroup
        :items="varieties"
        :name="'color-' + id"
        v-model="selected"
        class="color-options"
      />
    </template>
    <div class="title">
      {{ name }}
    </div>
    <span class="subtitle">
      {{ type }}
    </span>
    <div v-if="!isShort" class="card-row">
      <div class="labeled text">
        <span class="label">Price</span>
        <span class="content">
          <span class="price">{{ price }}</span>
          <Innopoint class="ml" />
        </span>
      </div>
      <Button
        @click="openModal(id)"
        label="view"
        outline
      />
    </div>
    <Button
      v-else
      @click="openModal(id)"
      label="view"
      outline
    />
  </Card>
</template>

<script>
  import Card from '../ui/card';
  import Button from '../ui/button';
  import RadioGroup from '../ui/radio-group';
  import Innopoint from '../../static/images/innopoint-sharp.svg';

  export default {
    name: 'StoreCard',
    components: { Button, Card, RadioGroup, Innopoint },
    props: {
      id: Number,
      name: String,
      type: String,
      price: Number,
      varieties: Array,
      isShort: Boolean,
    },
    data() {
      return {
        selected: this.varieties[0],
      };
    },
    methods: {
      openModal(id) {
        this.$router.push({name: 'store', query: {id: id}});
      },
    },
  };
</script>
