// src/containers/projects/filters.svelte
<script>
  import TextField from 'ui/text-field.svelte';
  import Dropdown from 'ui/dropdown.svelte';
  import Dot from 'ui/dot.svelte';
  import Button from 'ui/button.svelte';
  import RadioGroup from 'ui/radio-group.svelte';

  import Spots from '@/components/projects/spots.svelte';
  import Competences from '@/components/projects/competences.svelte';
  import DateRange from '@/components/projects/date.svelte';

  import orders from '@/constants/projects/order';
  import {selectedOrder, selectOrder, filters, changeSearch, clearAllFilters} from '@/store/projects';

  let open = null;
  const changeOpen = (name) => {
    if (open !== name) open = name;
    else open = null;
  };
</script>

<div class="filters">
  <TextField
      value={$filters.search}
      on:change={(e) => changeSearch(e.detail)}
      on:input={(e) => changeSearch(e.detail)}
      item
  >
    <svg src="images/icons/search.svg" class="item" />
  </TextField>
  <div class="dropdowns">
    <Dropdown chevron={false} wrapperclass="order-options">
      <svg slot="label" src="images/icons/order.svg" class="mr" />
      <span slot="label" class="tight">order</span>
      <span slot="label" class="regular">{$selectedOrder.label}</span>
      <RadioGroup
          selected={$selectedOrder}
          items={orders}
          isLabel
          on:change="{(e) => selectOrder(e.detail)}"
      />
    </Dropdown>

    <Dropdown chevron={false} right>
      <svg slot="label" src="images/icons/filter.svg" class="mr" />
      <span slot="label">filters</span>
      <span slot="label">{#if !$filters.isEmpty}<Dot active small />{/if}</span>

      <Button danger on:click={clearAllFilters}>Clear filters</Button>
      <ul class="accordion">
        <Spots />
        <Competences open={open === 'competences'} on:toggle={() => changeOpen('competences')} />
        <DateRange open={open === 'date'} on:toggle={() => changeOpen('date')} />
      </ul>
    </Dropdown>
  </div>
</div>

// containers/store/filters.vue
<template>
  <div class="filters">
    <TextField
      v-model="search"
      placeholder="Type to search"
      item="img"
      src="/images/icons/search.svg"
    />

    <Dropdown
      :chevron="false"
      right
    >
      <template v-slot:label>
        <FilterIcon class="mr" />
        filters
        <span class="dot active small" />
      </template>
      <Button @click="$store.dispatch('store/clearFilters')" danger>clear filters</Button>
      <ul class="accordion">
        <Price />
        <Colors />
      </ul>
    </Dropdown>
  </div>
</template>

<script>
  import TextField from '@/components/ui/text-field';
  import Dropdown from '@/components/ui/dropdown';
  import Button from '@/components/ui/button';
  import FilterIcon from '@/static/images/icons/filter.svg';
  import Price from '@/components/store/filters/price';
  import Colors from '@/components/store/filters/colors';

  export default {
    name: 'Filters',
    components: {
      TextField,
      Dropdown,
      Button,
      FilterIcon,
      Price,
      Colors,
    },
    data() {
      return {
      };
    },
    computed: {
      search: {
        get() {
          return this.$store.state.store.filters.search;
        },
        set(value) {
          return this.$store.commit('store/changeFilter', {type: 'search', value});
        },
      },
    },
    methods: {
    },
  };
</script>
