// src/components/store/product-card.svelte
<script>
  import Card from 'ui/card.svelte';
  import Button from 'ui/button.svelte';
  import Labeled from 'ui/labeled.svelte';
  import RadioGroup from 'ui/radio-group.svelte';
  import getBackground from '@/utils/optimal-color.js';
  import { groupByColor } from '@/utils/group-varieties.js';
  import { API_HOST } from '@/constants/env.js';

  export let id;
  export let name;
  export let type;
  export let price;
  export let varieties = [];
  export let short = false;

  let varietiesByColor = groupByColor(varieties);
  let colors = [...varietiesByColor.keys()];
  let selectedColor = colors[0];
  let altText = 'Product image: ';
  if (type) {
    altText += `"${name}" ${type}`;
  } else {
    altText += name;
  }
  $: imageURL = (
    varietiesByColor.get(selectedColor)[0].images.length !== 0 ?
      API_HOST + varietiesByColor.get(selectedColor)[0].images[0]
      : '/images/create-product/placeholder.svg'
  );
</script>

<Card classname="with-image">
  {#if colors.length > 1 && !short}
    <div class="image">
      <img
        src={imageURL}
        style="background: {getBackground(selectedColor)}"
        alt={altText}
      />
      <RadioGroup
        isColor
        items={colors.map(val => ({ value: val }))}
        bind:value={selectedColor}
        classname="color-options"
        name="color-{id}"
      />
    </div>
  {:else}
    <img
      src={imageURL}
      style="background: {getBackground(selectedColor)}"
      alt={altText}
      class="image"
    />
  {/if}

  <div class="content">
    <div class="title">{name}</div>
    {#if type}
      <div class="subtitle">{type}</div>
    {/if}
    {#if short}
      <Button href="/products/{id}" isOutline>view</Button>
    {:else}
      <div class="card-row">
        <Labeled label="Price">
          <span class="content">
            <span class="price">{price}</span>
            <svg src="images/innopoint-sharp.svg" class="innopoint" />
          </span>
        </Labeled>
        <Button href="/products/{id}" isOutline>view</Button>
      </div>
    {/if}
  </div>
</Card>

// containers/store/product-card.vue
<template>
  <div class="card product with-image">
    <Button
      v-if="closable"
      @click="closeModal"
      normal
      round
      class="close"
      img="/images/icons/x.svg"
    />
    <Carousel :images="activeVariety.images" :background="activeVariety.background" />
    <div class="content">
      <div class="title">{{ name }}</div>
      <div class="subtitle">{{ type }}</div>

      <Labeled class="text card-row" label="Description">
        {{ description }}
      </Labeled>

      <div class="card-row">
        <Labeled class="text" label="Colors">
          <RadioGroup
            :items="varieties"
            :name="'color-' + id"
            v-model="activeVariety"
            class="radio-options"
          />
        </Labeled>

        <div class="labeled text">
          <span class="label">Sizes</span>
          <div role="group" class="radio-options">
            <Chip
              v-for="(val, key) in activeVariety.sizes"
              :disabled="val === 0"
              :value="key === chosenSize"
              :key="key"
              @input="chooseSize(key)"
              name="sizes"
              small
            >
              {{ key }}
            </Chip>
          </div>
        </div>
      </div>

      <div class="card-row">
        <Labeled label="Price">
          <span class="price">
            {{ price }}
            <Innopoint />
          </span>
        </Labeled>

        <div class="purchase">
          <div class="purchases">{{ purchases }} purchases</div>
          <Button filled label="purchase" />
        </div>
      </div>
    </div>
  </div>
</template>

<script>
  import Carousel from "../../components/ui/carousel";
  import RadioGroup from "../../components/ui/radio-group";
  import Button from '../../components/ui/button';
  import Labeled from '../../components/ui/labeled';
  import Innopoint from '../../static/images/innopoint-sharp.svg';
  import Chip from '../../components/ui/chip';

  export default {
    name: "ProductCard",
    components: {
      Chip,
      Labeled,
      Button,
      Carousel,
      RadioGroup,
      Innopoint,
    },
    props: {
      id: Number,
      name: String,
      type: String,
      description: String,
      price: Number,
      purchases: Number,
      varieties: Array,
      closable: Boolean,
      toggleModal: Function,
    },
    data() {
      return {
        activeVariety: this.varieties[0],
        chosenSize: null,
      };
    },
    watch: {
      activeVariety() {
        this.chosenSize = null;
      },
    },
    methods: {
      closeModal() {
        this.$router.push({name: 'store', query: {}});
      },
      chooseSize(size) {
        this.chosenSize = size;
      },
    },
  };
</script>

<style scoped>
  .close {
    position: absolute !important;
  }
</style>
