// components/shop/tagline.vue
<template>
  <section class="tagline padded">
    <img src="/images/shop/voxel-trolley.png" class="hide-tb picture" />
    <div>
      <div class="headline">InnoStore</div>
      <div class="subhead">
        The place where your hard work and proactivity turns into cool merch of Innopolis University
      </div>
    </div>
  </section>
</template>

<script>
  export default {
    name: "ShopTagline",
  };
</script>

// src/containers/products/tagline.svelte
<script>
  import { onMount } from 'svelte';
  import { Button, Dot } from 'attractions';
  import Tagline from '@/components/common/tagline.svelte';
  import * as api from '@/utils/api.js';

  export let account;
  let dotShown = false;

  onMount(async () => {
    if (account && account.is_admin) {
      try {
        const purchases = await api.json(api.get('/stock_changes/for_review'));
        dotShown = purchases.length !== 0;
      } catch (e) {
        console.error(e);
      }
    }
  });

  const subhead = (
    'The place where your hard work and proactivity turns into cool merch of Innopolis University.'
  );
</script>

<Tagline
  imageURL="images/products/voxel-trolley.png"
  headline="InnoStore"
  {subhead}
>
  {#if account && account.is_admin}
    <div class="actions">
      <Button outline rectangle href="/products/new">
        <svg src="images/icons/plus.svg" class="mr" />
        create new product
      </Button>
      <Button outline rectangle href="/dashboard">
        <svg src="images/icons/shopping-bag.svg" class="mr" />
        manage purchases
        {#if dotShown}
          <Dot small />
        {/if}
      </Button>
    </div>
  {/if}
</Tagline>
