// components/ui/accordion.vue
<template>
  <div class="accordion">
    <div :class="{open}" class="panel">
      <slot name="label">
        <Button @click="toggle" chevron>{{ label }}</Button>
      </slot>
    </div>
    <section>
      <slot />
    </section>
  </div>
</template>

<script>
  import Button from './button';

  export default {
    components: {
      Button,
    },
    props: {
      label: {
        type: String,
      },
    },
    data() {
      return {
        open: false,
      };
    },
    methods: {
      toggle() {
        return this.open = !this.open;
      },
    },
  };
</script>

// src/components/ui/accordion.svelte
<script>
  import Button from './button.svelte';

  export let label = '';
  export let open = false;
  export const toggle = () => (open = !open);
</script>

<div class="accordion">
  <div class:open class="panel">
    <slot name="label">
      <Button on:click={toggle} chevron>{label}</Button>
    </slot>
  </div>
  <section>
    <slot />
  </section>
</div>
