// components/ui/button.vue
<template>
  <!--eslint-disable-next-line-->
  <component
    :is="component"
    :class="classes"
    :href="linkTo"
    :to="linkTo"
    :target="target"
    :disabled="disable"
    v-ripple="ripple"
    @click="handleClick"
    type="button"
  >
    <template v-if="badge">
      <div class="badge">
        <!--eslint-disable-next-line-->
        <component v-if="img" :is="svg" :class="[label && 'mr']" />
      </div>
    </template>

    <template v-else-if="img">
      <!--eslint-disable-next-line-->
      <component v-if="img" :is="svg" :class="[label && 'mr']" />
    </template>
    <slot>
      {{ label }}
    </slot>
  </component>
</template>

<script>

  export default {
    name: 'Button',
    props: {
      label: {
        type: String,
        default: '',
      },
      link: {
        type: Boolean,
        default: false,
      },
      away: {
        type: Boolean,
        default: false,
      },
      href: {
        type: String,
        default: '#',
      },
      img: {
        type: String,
        default: '',
      },
      click: Function,
      filled: {
        type: Boolean,
        default: false,
      },
      disabled: {
        type: Boolean,
        default: false,
      },
      outline: {
        type: Boolean,
        default: false,
      },
      danger: {
        type: Boolean,
        default: false,
      },
      badge: {
        type: Boolean,
        default: false,
      },
      round: {
        type: Boolean,
        default: false,
      },
      normal: {
        type: Boolean,
        default: false,
      },
    },
    computed: {
      svg() {
        if(this.img) return () => import('../../static' + this.img);
        return '';
      },
      component() {
        return (this.link && this.href) ? (this.away || this.href.match(/#.+/i)) ? 'a' : 'nuxt-link' : 'button';
      },
      ripple() {
        if(this.filled) {
          return 'rgba(255, 255, 255, .35)';
        } else if(this.danger) {
          return 'rgba(186, 3, 3, .25)';
        } else {
          return 'rgba(56, 120, 0, .25)';
        }
      },
      linkTo() {
        if(this.link && this.href) {
          return this.href;
        }
        return null;
      },
      target() {
        if(this.link && this.away) return '_blank';
        return null;
      },
      classes() {
        let arr = ['btn'];
        // 'btn', filled && 'filled', outline && 'outline', danger && 'danger', round && 'round', normal && 'normal'
        if(this.filled) arr.push('filled');
        if(this.outline) arr.push('outline');
        if(this.danger) arr.push('danger');
        if(this.round) arr.push('round');
        if(this.normal) arr.push('normal');
        return arr;
      },
      disable() {
        if(!this.link && this.disabled) return true;
        return null;
      },
    },
    methods: {
      handleClick() {
        this.$emit('click');
      },
    },
  };
</script>

// src/components/ui/button.svelte
<script>
  import { createEventDispatcher } from 'svelte';

  export let label = '';
  export let away = null;
  export let href = '';
  export let chevron = false;
  export let filled = false;
  export let disabled = false;
  export let outline = false;
  export let danger = false;
  export let badge = false;
  export let round = false;
  export let normal = false;

  $: ripple = filled
    ? 'rgba(255, 255, 255, .35)'
    : danger
    ? 'rgba(186, 3, 3, .25)'
    : 'rgba(56, 120, 0, .25)';
  $: classes = [
    'btn',
    filled && 'filled',
    outline && 'outline',
    danger && 'danger',
    round && 'round',
    normal && 'normal',
  ].filter(v => v !== false);

  let dispatch = createEventDispatcher();
</script>

{#if href}
  <a {href} target={away && '_blank'} class={classes.join(' ')}>
    <slot />
    {#if away}
      <svg src="images/icons/external-link.svg" class="icon ml" />
    {/if}
  </a>
{:else}
  <button
    type="button"
    {disabled}
    class={classes.join(' ')}
    on:click={() => dispatch('click')}>
    {#if badge}
      <div class="badge">
        <slot>{label}</slot>
      </div>
    {:else}
      <slot>{label}</slot>
    {/if}

    {#if chevron}
      <svg src="images/icons/chevron-down.svg" class="icon ml chevron" />
    {/if}
  </button>
{/if}
