// components/ui/dot.vue
<template>
  <span :class="classes" />
</template>

<script>
  export default {
    name: 'Dot',
    props: {
      small: Boolean,
      attention: Boolean,
      active: Boolean
    },
    computed: {
      classes() {
        let arr = ['dot'];
        if(this.small) arr.push('small');
        if(this.attention) {
          arr.push('attention');
        } else if(this.active) {
          arr.push('active');
        } else {
          arr.push('new');
        }
        return arr;
      }
    }
  };
</script>

<style scoped>
  .dot {
    display: inline-block;
  }
</style>

// src/components/ui/dot.svelte
<script>
  export let small = false;
  export let attention = false;
  export let active = false;
  export let classname = '';

  $: classes = [
    classname && classname,
    small && 'small',
    !attention ? (!active ? 'new' : 'active') : 'attention',
  ].filter(v => v !== false);
</script>

<span class="dot {classes.join(' ')}" />
