// components/ui/labeled.vue
<template>
  <div :class="!icon && 'text'" class="labeled">
    <template v-if="icon">
      <!--eslint-disable-next-line-->
      <component :is="svg" />
      <div class="text">
        <span class="label">{{ label }}</span>
        <span>
          <slot />
        </span>
      </div>
    </template>

    <template v-else>
      <span class="label">{{ label }}</span>
      <span>
        <slot />
      </span>
    </template>
  </div>
</template>

<script>
  export default {
    name: 'Labeled',
    props: {
      icon: {
        type: String,
        default: null
      },
      label: {
        type: String,
        required: true
      }
    },
    computed: {
      svg() {
        if(this.icon) return () => import('../../static' + this.icon);
        return '';
      }
    }
  };
</script>

// src/components/ui/labeled.svelte
<script>
  export let label = '';
  export let icon = null;
</script>

<div class:text={!icon} class="labeled">
  {#if icon}
    <slot name="icon" />
    <div class="text">
      <span class="label">{label}</span>
      <span>
        <slot />
      </span>
    </div>
  {:else}
    <span class="label">{label}</span>
    <span>
      <slot />
    </span>
  {/if}
</div>
