// components/profile/radio-group.vue
<template>
  <div role="group" class="switches with-labels">
    <label
      v-for="item in items"
      :key="item.id"
      class="clickable"
    >
      <span class="label">{{ item.label }}</span>
      <div class="radio">
        <input
          :checked="selected === item"
          @change="select(item)"
          :name="name"
          type="radio"
        />
        <div class="icon" />
      </div>
    </label>
  </div>
</template>

<script>
  const items = [
    {
      id: 0,
      label: 'Push',
    },
    {
      id: 1,
      label: 'Off',
    },
    {
      id: 2,
      label: 'Email',
    },
  ];

  export default {
    name: 'ProfileRadioGroup',
    props: {
      name: {
        type: String,
        required: true,
      },
      value: {
        type: Object,
      },
    },
    data() {
      return {
        items,
        selected: null,
      };
    },
    watch: {
      value: {
        immediate: true,
        handler(value) {
          this.selected = value;
        },
      },
    },
    methods: {
      select(item) {
        this.selected = item;
        this.$emit('input', item);
      },
    },

  };
</script>

// src/components/ui/radio-group.svelte
<script>
  import { createEventDispatcher } from 'svelte';

  export let items = [];
  export let name;
  export let classname;
  export let selected = {};
  export let isLabel = false;
  export let isLabelGreen = false;
  export let labelPosition = 'right';
  export let labelClass = '';

  $: selectedId = selected.id || null;

  let dispatch = createEventDispatcher();

  const changeRadio = (item) => {
    selectedId = item.id;
    dispatch('change', item);
  };
</script>

<!--
<div :class="{'with-labels': withLabels, horizontal}" class="radio-group" role="group">
  <label
    v-for="(item, index) in items"
    :key="index"
    :class="{clickable: withLabels, colored: !!item.color}"
    class="radio"
  >
    <input
      :checked="selected === item"
      @change="select(item)"
      :name="name"
      type="radio"
    />
    <div :class="{white: isWhite(item)}" :style="style(item)" class="icon" />
    {{ (withLabels && item.label) ? item.label : '' }}
  </label>
</div>
-->

<div class:with-labels={isLabel} class={classname} role="group">
  {#each items as item, i (i)}
    <label class:clickable={isLabel} class={labelClass}>
      {#if isLabel}
        {#if labelPosition === 'left'}
          {#if isLabelGreen}
            <span class="label">{item.label}</span>
          {:else}
            {item.label}
          {/if}
        {/if}

        <div class="radio">
          <input
              on:change="{() => changeRadio(item)}"
              type="radio"
              name={name}
              checked="{selectedId === item.id}"
          >
          <div class="icon"></div>
        </div>

        {#if labelPosition === 'right'}
          {#if isLabelGreen}
            <span class="label">{item.label}</span>
          {:else}
            {item.label}
          {/if}
        {/if}

      {:else}
        <input on:change="{() => changeRadio(item)}" type="radio" name={name} checked={item.checked}>
        <div class="icon"></div>
      {/if}
    </label>
  {/each}
</div>
