// components/ui/radio-group.vue
<template>
  <div :class="withLabels && 'with-labels'" role="group">
    <label
      v-for="(item, index) in data"
      :key="index"
      :class="withLabels && 'clickable'"
      class="radio"
    >
      <div class="radio">
        <input
          :checked="item.checked"
          @change="changeItems(index)"
          :name="name"
          type="radio"
        />
        <div :style="style(item)" class="icon" />
      </div>
      {{ (withLabels && item.label) ? item.label : '' }}
    </label>
  </div>
</template>

<script>
  export default {
    name: 'RadioGroup',
    props: {
      name: {
        type: String,
        required: true,
      },
      items: {
        type: Array,
        required: true,
      },
      click: {
        type: Function,
        required: true,
      },
      withLabels: {
        type: Boolean,
        default: false,
      },
      withColors: {
        type: Boolean,
        default: false,
      },
    },
    data() {
      return {
        data: this.items,
      };
    },
    methods: {
      changeItems(index) {
        this.data[index] = !this.data[index];
        this.click(this.data);
      },
      style(item) {
        if(this.withColors) {
          return `
          background-color: ${item.color};
          border-color: ${item.color};
        `;
        }
        return '';
      },
    },
  };
</script>

// src/components/ui/radio-group.svelte
<script>
  import { createEventDispatcher } from 'svelte';

  export let items = [];
  export let name;
  export let classname;
  export let selected = {};
  export let isLabel = false;
  export let isLabelGreen = false;
  export let labelPosition = 'right';
  export let labelClass = '';

  $: selectedId = selected.id || null;

  let dispatch = createEventDispatcher();

  const changeRadio = (item) => {
    selectedId = item.id;
    dispatch('change', item);
  };
</script>

<!--
<div :class="{'with-labels': withLabels, horizontal}" class="radio-group" role="group">
  <label
    v-for="(item, index) in items"
    :key="index"
    :class="{clickable: withLabels, colored: !!item.color}"
    class="radio"
  >
    <input
      :checked="selected === item"
      @change="select(item)"
      :name="name"
      type="radio"
    />
    <div :class="{white: isWhite(item)}" :style="style(item)" class="icon" />
    {{ (withLabels && item.label) ? item.label : '' }}
  </label>
</div>
-->

<div class:with-labels={isLabel} class={classname} role="group">
  {#each items as item, i (i)}
    <label class:clickable={isLabel} class={labelClass}>
      {#if isLabel}
        {#if labelPosition === 'left'}
          {#if isLabelGreen}
            <span class="label">{item.label}</span>
          {:else}
            {item.label}
          {/if}
        {/if}

        <div class="radio">
          <input
              on:change="{() => changeRadio(item)}"
              type="radio"
              name={name}
              checked="{selectedId === item.id}"
          >
          <div class="icon"></div>
        </div>

        {#if labelPosition === 'right'}
          {#if isLabelGreen}
            <span class="label">{item.label}</span>
          {:else}
            {item.label}
          {/if}
        {/if}

      {:else}
        <input on:change="{() => changeRadio(item)}" type="radio" name={name} checked={item.checked}>
        <div class="icon"></div>
      {/if}
    </label>
  {/each}
</div>
