// components/ui/text-field.vue
<template>
  <div :class="classes">
    <template v-if="multiline">
      <textarea
        :id="id"
        :placeholder="placeholder"
        :name="name"
        :value="value"
        @focus="handleFocus"
        @blur="handleBlur"
        @input="handleInput"
        cols="5"
      />
    </template>
    <template v-else>
      <input
        :type="type"
        :placeholder="placeholder"
        :name="name"
        :value="value"
        :id="id"
        :pattern="pattern"
        :min="min"
        :max="max"
        @focus="handleFocus"
        @blur="handleBlur"
        @input="handleInput"
      />

      <label v-if="outline" :for="id" class="label">{{ label }}</label>

      <template v-if="item">
        <span
          v-if="item === 'text'"
          class="item"
        >
          {{ text }}
        </span>

        <img
          v-else-if="item === 'img'"
          :src="src"
          class="item"
          alt=""
        />
      </template>

      <span v-if="pattern" class="error"> {{ error }}</span>
    </template>
  </div>
</template>

<script>
  export default {
    name: 'TextField',
    props: {

      // Wrapper props
      item: {
        type: String,
        default: '',
      },
      right: {
        type: Boolean,
        default: false,
      },
      src: String,
      text: String,

      // Outline component requires label and id props
      outline: {
        type: Boolean,
        default: false,
      },
      label: String,
      id: String,

      // Input props
      type: {
        type: String,
        default: 'text',
      },
      disabled: {
        type: Boolean,
        default: false,
      },
      multiline: {
        type: Boolean,
        default: false,
      },
      value: [String, Number],
      placeholder: String,
      pattern: String,
      error: String,
      name: String,
      min: Number,
      max: Number,
      focus: Function,
      input: Function,
      blur: Function,
    },
    computed: {
      classes() {
        let arr = ['text-field'];
        if(this.item) {
          if(this.right) {
            arr.push('with-item', 'right');
          } else {
            arr.push('with-item', 'left');
          }
        }
        if(this.outline) arr.push('outline');

        return arr;
      },
    },
    methods: {
      handleFocus() {
        if(this.focus) this.focus();
      },
      handleBlur() {
        if(this.blur) this.blur();
        this.$emit('change', this.checkNumber(event.target.value));
      },
      handleInput(event) {
        if(this.input) this.input();
        this.$emit('input', this.checkNumber(event.target.value));
      },
      checkNumber(value) {
        if(this.type == 'number') {
          return window.parseInt(value, 10);
        }
        return value;
      },
    },
  };
</script>

// src/components/ui/text-field.svelte
<script>
  import { createEventDispatcher } from 'svelte';

  export let id = null;
  export let classname = null;
  export let placeholder = '';
  export let name = null;
  export let type = null;
  export let value = null;
  export let cols = null;
  export let pattern = null;
  export let min = null;
  export let max = null;
  export let maxLength = null;
  export let label = null;
  export let error = null;
  export let text = null;
  export let item = null;
  export let multiline = null;
  export let outline = null;
  export let right = null;

  $: classes = [
    'text-field',
    classname && classname,
    item && 'with-item',
    item && ((right && 'right') || 'left'),
    outline && 'outline',
  ].filter(v => v !== false);

  let dispatch = createEventDispatcher();
</script>

<div class={classes.join(' ')}>
  {#if multiline}
    <textarea
      {id}
      {placeholder}
      {name}
      bind:value
      cols={5}
      on:focus={() => dispatch('focus')}
      on:blur={() => dispatch('blur')}
      on:input={() => dispatch('input')}
      on:change={(e) => dispatch('change', e.target.value)}
    />
  {:else}
    <input
      {id}
      type="text"
      {placeholder}
      {name}
      {type}
      bind:value
      {pattern}
      {min}
      {max}
      {maxLength}
      on:focus={() => dispatch('focus')}
      on:blur={() => dispatch('blur')}
      on:input={() => dispatch('input')}
      on:keyup.enter={() => dispatch('blur')}
      on:change={(e) => dispatch('change', e.target.value)}
    />

    {#if outline}
      <label for={id} class="label">{label}</label>
    {/if}

    {#if item}
      <slot />
    {/if}

    {#if pattern}
      <span class="error">{error}</span>
    {/if}
  {/if}
</div>
